site_name: 杨小哥博客


# theme: readthedocs


nav:
  - 算法:
    # - 数据结构和算法思维导图: 算法/数据结构和算法思维导图.md
    # - leetcode:
    #   - 数组:
    #     - 6.Z字形变换: leetcode/数组/6.Z字形变换.md 
    #     - 11. 盛最多水的容器: leetcode/数组/11. 盛最多水的容器.md 
    #     - 26.删除排序数组中的重复项: leetcode/数组/26.删除排序数组中的重复项.md 
    #     - 27.移除元素: leetcode/数组/27.移除元素.md
    #     - 35. 搜索插入位置: leetcode/数组/35. 搜索插入位置.md
    #   - 链表:
    #     - 19. 删除链表的倒数第N个节点: leetcode/链表/19. 删除链表的倒数第N个节点.md 
    #     - 21. 合并两个有序链表: leetcode/链表/21. 合并两个有序链表.md 
    #     - 23. 合并K个排序链表(可以优化): leetcode/链表/23. 合并K个排序链表(可以优化).md 
    #     - 24. 两两交换链表中的节点: leetcode/链表/24. 两两交换链表中的节点.md 
    #     - 206. 反转链表: leetcode/链表/206. 反转链表.md 
    # - 数据结构和算法:
    #   - 1. 复杂度分析-上: 算法/复杂度分析-上.md
    #   - 2. 复杂度分析-下: 算法/复杂度分析-下.md
    #   - 3. 数组: 算法/数组.md
    #   - 4. 链表-上: 算法/链表-上.md
    #   - 5. 链表-下: 算法/链表-下.md
    #   - 6. 栈: 算法/栈.md
    #   - 点开:
    #     - 基本排序算法: 算法/基本排序算法.md
    #     - 分治法和归并排序: 算法/分治法和归并排序.md
    #     - 滑动窗口原理: 算法/滑动窗口原理.md
    # - 练习:
    #   - 二分查找:
    #     - 寻找旋转排序数组中的最小值: 算法练习题/寻找旋转排序数组中的最小值.md
    #   -
    - 位运算: 蓝桥学院/位运算.md

  - lua:
    - lua 表的构造: lua/表的构造.md
    - lua select 函数: lua/select函数.md
    - lua 面向对象: lua/opp.md
    - pairs和ipairs: lua/pairs和ipairs.md
    - 错误处理 pcall & xpcall: lua/错误处理 pcall & xpcall.md
    - 协程实现生产者消费者: lua/协程实现生产者消费者.md
    - lua 单链表: lua/lua 实现单链表.md
  - skynet:
    - 1. 并发编程和并行编程: skynet/并发编程和并行编程.md
    - 2. skynet 基于 Actor 模式的开源框架: skynet/skynet 基于 Actor 模式的开源框架.md
  - python:
    - python 语法: 
      - 1. python相关介绍: python/python相关介绍.md
      - 2. python基础语法: python/python基础语法.md
      - 3. 字符串: python/python字符串.md
      - 4. 循环: python/python循环.md
      - 5. 列表: python/python列表.md
      - 6. 元组: python/python元组.md
      - 7. 字典: python/python字典.md
      - 8. 集合: python/python集合.md
      - 9. 函数: python/python函数.md
      - 10. 作用域: python/python作用域.md
      - 11. 高阶函数: python/python高阶函数.md
      - 12. 递归: python/python递归.md
      - 13. 装饰器: python/python装饰器.md
      - 14. 模块: python/python模块.md
      - 15. 包: python/python包.md
      - 16. 异常: python/python异常.md
      - 17. 迭代器和生成器: python/python迭代器和生成器.md
      - 18. 字节串和字节数组: python/字节串和字节数组.md
      - 19. 文件读写: python/文件读写.md
      - 20. 字符编码: python/字符编码.md
      - 21. 面向对象编程: 
          - 基本语法: python/面向对象编程.md
          - 继承派生: python/继承派生.md
      - 22. 迭代器（高级）: python/迭代器（高级）.md
      - 补充知识点: python/补充知识点.md
    - django: 
      - 1. django介绍及安装: django/1_django介绍及安装.md
      - 2. django中的路由: django/2_django中的路由.md
      - 3. HttpRequest对象: django/3_django中的HttpRequest对象.md
      - 4. session和cookie: django/4_django中的session和cookie.md
      - 5. django中的模板: django/5_django中的模板.md
      - 6. django中的模型: django/6_django中的模型.md
      - 7. 模型中的关系映射: django/7_django模型中的关系映射.md
      - 8. 自带的后台管理: django/8_django自带的后台管理.md
      - 9. django视图之CBV的基本使用: drf/1.django视图之CBV的基本使用.md
      - 10. CBV中解决csrf认证的问题: drf/2.CBV中解决csrf认证的问题.md
  - 工具:
    - linux操作系统: tools/linux操作系统.md
  - 理财:
    - 基金理财: skynet/并.md
  